
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){

   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });

}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Siswa France Track      <small><?= cclang('detail', ['Siswa France Track']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/siswa_ft'); ?>">Siswa France Track</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Siswa France Track</h3>
                     <h5 class="widget-user-desc">Detail Siswa France Track</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_siswa_ft" id="form_siswa_ft" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Siswa Ft </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->id_siswa_ft); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Lengkap </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->nama_lengkap); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email Ms. Office </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->email_ms_office); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NISN </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->nisn); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->tempat_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->tgl_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->jenis_kelamin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Agama </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->agama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email Ms. Office Ortu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->email_ms_office_ortu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->nama_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->pekerjaan_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->notelp_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->nama_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->pekerjaan_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->notelp_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->alamat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->areas_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->districts_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kota </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->regencies_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Provinsi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->provinces_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Pos </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->kode_pos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->sekolah_asal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Foto Peserta </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_ft->foto_peserta)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->foto_peserta; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->foto_peserta; ?>" class="image-responsive" alt="image siswa_ft" title="foto_peserta siswa_ft" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_ft/' . $siswa_ft->foto_peserta; ?>">
                                 <img src="<?= get_icon_file($siswa_ft->foto_peserta); ?>" class="image-responsive" alt="image siswa_ft" title="foto_peserta <?= $siswa_ft->foto_peserta; ?>" width="40px"> 
                               <?= $siswa_ft->foto_peserta ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Akte Lahir </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_ft->akte_lahir)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->akte_lahir; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->akte_lahir; ?>" class="image-responsive" alt="image siswa_ft" title="akte_lahir siswa_ft" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_ft/' . $siswa_ft->akte_lahir; ?>">
                                 <img src="<?= get_icon_file($siswa_ft->akte_lahir); ?>" class="image-responsive" alt="image siswa_ft" title="akte_lahir <?= $siswa_ft->akte_lahir; ?>" width="40px"> 
                               <?= $siswa_ft->akte_lahir ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Kartu Keluraga </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_ft->kartu_keluarga)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->kartu_keluarga; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_ft/' . $siswa_ft->kartu_keluarga; ?>" class="image-responsive" alt="image siswa_ft" title="kartu_keluarga siswa_ft" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_ft/' . $siswa_ft->kartu_keluarga; ?>">
                                 <img src="<?= get_icon_file($siswa_ft->kartu_keluarga); ?>" class="image-responsive" alt="image siswa_ft" title="kartu_keluarga <?= $siswa_ft->kartu_keluarga; ?>" width="40px"> 
                               <?= $siswa_ft->kartu_keluarga ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber Informasi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->sumber_informasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alasan Tertarik </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->alasan_tertarik); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Peminatan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->peminatan_ft_peminatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Lulus </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->status_lulus_status_lulus); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nomor Transaksi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->no_transaksi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nomor Peserta </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->no_peserta); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Virtual Account </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_ft->va_number); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('siswa_ft_update', function() use ($siswa_ft){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit siswa_ft (Ctrl+e)" href="<?= site_url('administrator/siswa_ft/edit/'.$siswa_ft->id_siswa_ft); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Siswa Ft']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/siswa_ft/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Siswa Ft']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
