
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){

   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });

}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Siswa TK      <small><?= cclang('detail', ['Siswa TK']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/siswa_tk'); ?>">Siswa TK</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Siswa TK</h3>
                     <h5 class="widget-user-desc">Detail Siswa TK</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_siswa_tk" id="form_siswa_tk" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Siswa TK </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->id_siswa_tk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Lengkap </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->nama_lengkap); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email Ms. Office </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->email_ms_office); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NISN </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->nisn); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->tempat_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->tgl_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->jenis_kelamin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Agama </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->agama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email Ms. Office Ortu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->email_ms_office_ortu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->nama_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->pekerjaan_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->notelp_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->nama_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->pekerjaan_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->notelp_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->alamat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Provinsi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->provinces_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->areas_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->districts_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kota </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->regencies_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Pos </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->kode_pos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->sekolah_asal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Foto Peserta </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_tk->foto_peserta)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->foto_peserta; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->foto_peserta; ?>" class="image-responsive" alt="image siswa_tk" title="foto_peserta siswa_tk" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_tk/' . $siswa_tk->foto_peserta; ?>">
                                 <img src="<?= get_icon_file($siswa_tk->foto_peserta); ?>" class="image-responsive" alt="image siswa_tk" title="foto_peserta <?= $siswa_tk->foto_peserta; ?>" width="40px"> 
                               <?= $siswa_tk->foto_peserta ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Akte Lahir </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_tk->akte_lahir)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->akte_lahir; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->akte_lahir; ?>" class="image-responsive" alt="image siswa_tk" title="akte_lahir siswa_tk" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_tk/' . $siswa_tk->akte_lahir; ?>">
                                 <img src="<?= get_icon_file($siswa_tk->akte_lahir); ?>" class="image-responsive" alt="image siswa_tk" title="akte_lahir <?= $siswa_tk->akte_lahir; ?>" width="40px"> 
                               <?= $siswa_tk->akte_lahir ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Kartu Keluraga </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa_tk->kartu_keluarga)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->kartu_keluarga; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa_tk/' . $siswa_tk->kartu_keluarga; ?>" class="image-responsive" alt="image siswa_tk" title="kartu_keluarga siswa_tk" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa_tk/' . $siswa_tk->kartu_keluarga; ?>">
                                 <img src="<?= get_icon_file($siswa_tk->kartu_keluarga); ?>" class="image-responsive" alt="image siswa_tk" title="kartu_keluarga <?= $siswa_tk->kartu_keluarga; ?>" width="40px"> 
                               <?= $siswa_tk->kartu_keluarga ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber Informasi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->sumber_informasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alasan Tertarik </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->alasan_tertarik); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tingkatan </label>

                        <div class="col-sm-8">
                           <?php $tingkatan_row = $this->mymodel->getbywhere('tingkatan_tk', 'id_tingkatan_tk', $siswa_tk->id_tingkatan, 'row'); echo _ent(!empty($tingkatan_row) ? $tingkatan_row->label : $siswa_tk->id_tingkatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Mutasi? </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->is_mutasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelas Mutasi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->kelas_mutasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Lulus </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->status_lulus_status_lulus); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Peserta Ujian </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->no_peserta); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Transaksi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->no_transaksi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Provinsi Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->provinces_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kota Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->regencies_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->districts_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelurahan Sekolah Asal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->areas_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Virtual Account </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa_tk->va_number); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('siswa_tk_update', function() use ($siswa_tk){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit siswa_tk (Ctrl+e)" href="<?= site_url('administrator/siswa_tk/edit/'.$siswa_tk->id_siswa_tk); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Siswa TK']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/siswa_tk/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Siswa TK']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
